### ISSUE TITLE
 "erreur de segmentation (core dumped)" à l'exécution de smah.generate_mesh

### ISSUE THREAD

**Issue by CatherineFouchier** [DassHydro-dev/smash#31]
Le 2ème bassin du fichier attaché fait bloquer l'exécution de maillage ci-dessous.
Elle s'exécute en revanche correctement quand elle est spécifiée avec l'argument max_depth = 1

[liste_2bv.csv](https://github.com/DassHydro-dev/smash/files/11868913/liste_2bv.csv)

```
stations = pd.read_csv("2bv.csv", sep=",", decimal=".")
# Boucle pour mailler les bassins (
for i in range(len(stations)):
	mesh2 = smash.generate_mesh(
	    path=flwdir,
	    x=stations.loc[i, "Xexu"],
	    y=stations.loc[i, "Yexu"],
	    area=stations.loc[i, "Surf_raster"]*1e6,
	    code=stations.loc[i, "Code_BV"],
	    max_depth=2
	)
	smash.save_mesh(mesh2, f"Mesh/mesh_{stations.loc[i, 'Code_BV']}.hdf5")
```

**Comment by inoelloc** [comment]
Cette erreur se produit quand deux cellules voisines ont des directions d'écoulement antagonistes ( [1, 5], [2, 6], [3, 7], [4, 8]).
Ce type de cas devrait être directement corrigé dans le fichier des directions d'écoulement.
Pour éviter des segmentation faults pour un nombre maximum de recurssion atteint, un check est ajouté dans le code pour sortir de la recursion si besoin
