### ISSUE TITLE
Warning in signatures computation

### ISSUE THREAD

**Issue by ThomasdeFournas** [DassHydro-dev/smash#65]
- FutureWarning
`/home/tdefournas/smash-dev/smash/smash/core/signal_analysis/segmentation/segmentation.py:134: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
    df = pd.concat([df, pdrow], ignore_index=True)`

Pandas version used: pandas v2.1.0

**Comment by nghi-truyen** [comment]
The problem has been resolved in PR #66
