### ISSUE TITLE
Final states are not computed in case of regionalization with ANN mapping

### ISSUE THREAD

**Issue by nghi-truyen** [DassHydro-dev/smash#76]
```python3
model.optimize(mapping="ann")
model.get_opr_final_states("hp")
```
```bash
array([[-99., -99., -99., -99., -99., -99., -99., -99., -99., -99., -99.,
        -99., -99., -99.],
       ...
       [-99., -99., -99., -99., -99., -99., -99., -99., -99., -99., -99.,
        -99., -99., -99.]], dtype=float32)
```
Final states are not computed.

**Comment by nghi-truyen** [comment]
@inoelloc je pense à rajouter un forward run à la fin d'optimisation avec ANN pour updater les états finaux, je sais pas si c'est une bonne idée de faire ça ?

**Comment by inoelloc** [comment]
Oui je ferais ca. Ca mettra a jour les états finaux (peut etre que les debit simulés sont pas non plus à jour avec les paramètres optimisés donc oui pour un forward en fin d'optimisation)

**Comment by nghi-truyen** [comment]
En fait si j'ai bien compris, le problème c'est que forward_b qui est appelé à chaque itération dans ANN ne permet pas à updater les états finaux. Donc à priori, tous les paramètres comme les q_sim et cost doivent être updated au cours d'optimisation. Du coup je vais créer un PR pour résoudre ce problème.

**Comment by nghi-truyen** [comment]
Resolved in PR #77.
